services:
  nginx-leave-application-portal:
    image: kin252867/docker-nginx-leaveapplicationportal:ver1.1
    container_name: nginx-leave-application-portal
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge